# Generated by Django 5.2.6 on 2025-09-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypermission',
            name='permission_type',
            field=models.CharField(help_text='Ex: read, write, admin', max_length=50, verbose_name='Tipo de Permissão'),
        ),
    ]
