# Generated by Django 5.2.6 on 2025-09-24 15:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_companypermission_permission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#6B7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
                'unique_together': {('nome', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(help_text='Formato: +5548999999999', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato internacional: +5548999999999', regex='^\\+[1-9]\\d{1,14}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('origem', models.CharField(blank=True, help_text='Como o contato foi adicionado (importação, manual, API, etc.)', max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='accounts.company')),
                ('tags', models.ManyToManyField(blank=True, related_name='contatos', to='wpp.tag')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['company', 'ativo'], name='wpp_contact_company_740f82_idx'), models.Index(fields=['telefone'], name='wpp_contact_telefon_b54e1b_idx'), models.Index(fields=['created_at'], name='wpp_contact_created_cd46c5_idx')],
                'unique_together': {('telefone', 'company')},
            },
        ),
    ]
