# Generated by Django 5.2.6 on 2025-09-25 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companypermission_permission_type'),
        ('wpp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Aniversário, Promoção Black Friday, Cobrança, etc.', max_length=100, verbose_name='Nome da Campanha')),
                ('texto', models.TextField(help_text='Use {{nome}} para incluir o nome do contato automaticamente', verbose_name='Texto da Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Campanha Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='accounts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
                'unique_together': {('nome', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Aniversariantes Janeiro 2024', max_length=150, verbose_name='Nome do Envio')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviada', 'Enviada'), ('erro', 'Erro com Falhas'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='Status')),
                ('total_contatos', models.IntegerField(default=0, verbose_name='Total de Contatos')),
                ('total_enviados', models.IntegerField(default=0, verbose_name='Enviados com Sucesso')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Erros no Envio')),
                ('data_agendamento', models.DateTimeField(blank=True, help_text='Deixe em branco para enviar imediatamente', null=True, verbose_name='Agendar para')),
                ('timeout_envio', models.IntegerField(default=2, help_text='Intervalo entre cada envio para evitar spam', verbose_name='Timeout entre envios (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_envio_iniciado', models.DateTimeField(blank=True, null=True, verbose_name='Envio Iniciado em')),
                ('data_envio_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Envio Finalizado em')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='wpp.campaign', verbose_name='Campanha')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='accounts.company', verbose_name='Empresa')),
                ('contatos', models.ManyToManyField(related_name='mensagens_recebidas', to='wpp.contact', verbose_name='Contatos Selecionados')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Envio de Mensagem',
                'verbose_name_plural': 'Envios de Mensagens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('texto_enviado', models.TextField(verbose_name='Texto Enviado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('response_api', models.JSONField(blank=True, default=dict, verbose_name='Resposta da API')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_mensagens', to='wpp.contact', verbose_name='Contato')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wpp.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Log de Mensagem',
                'verbose_name_plural': 'Logs de Mensagens',
                'ordering': ['-created_at'],
                'unique_together': {('message', 'contato')},
            },
        ),
    ]
