# Generated by Django 5.1.2 on 2024-10-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('contato', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/cadastro/clientes/')),
                ('status', models.CharField(default='Ativo', max_length=255)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('contato', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/cadastro/clientes/')),
                ('status', models.CharField(default='Ativo', max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
