# Generated by Django 5.1.2 on 2024-10-26 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddConstraint(
            model_name='pessoafisica',
            constraint=models.UniqueConstraint(fields=('empresa', 'cpf_cnpj'), name='unico_cpf_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='pessoajuridica',
            constraint=models.UniqueConstraint(fields=('empresa', 'cpf_cnpj'), name='unico_cnpj_por_empresa'),
        ),
    ]
